### ISSUE TITLE
Targeting Specific rows / columns in Grid. nth-row()? 

### ISSUE THREAD

**Issue by wesbos** [rachelandrew/cssgrid-ama#115]
I know this isn't possible right now, but was it ever discussed? Curious to hear your thoughts on it. 

Say we have a nav that is two levels deep, the top level is nice and big, and as items get knocked onto the second level, you could target them and style differently. 

Something like this: 

```css
    nav {
      display: grid;
      /* Fit as many as we can on each line, min 150px */
      grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
    }
    
    nav a {
      font-size: 20px; /* Large first row items */
    }
    
    nav:nth-row(2) a {
      font-size: 12px; /* Smaller second row item */
    }
```
