### ISSUE TITLE
Only show grid track if it has content

### ISSUE THREAD

**Issue by MidnightDesign** [rachelandrew/cssgrid-ama#43]
Is there a way to hide a grid track/area if it is empty/has no elements? Something with `minmax()` probably?

**Comment by rachelandrew** [comment]
If I track has a nice of auto and there is nothing in the track then it will collapse. I'm not sure if that is the question though - do you have an example in code?

**Comment by MidnightDesign** [comment]
```html
<header>
  <!-- <button>Go back</button> -->
  <h1>My Grid Test</h1>
</header>
```

```css
header {
    display: grid;
    grid-template-columns: 20px 1fr;
    grid-template-areas: "back title";
    background-color: red;
}
button {
    width: 20px;
}
h1 {
  margin: 0;
  grid-area: title;
  background-color: white;
}
```

I want the `h1` to be aligned with the left edge of the grid container since there is no button.

[Fiddle](https://jsfiddle.net/nru82Lss/)
