### ISSUE TITLE
do gutters count when using grid-row and grid-column?

### ISSUE THREAD

**Issue by caraya** [rachelandrew/cssgrid-ama#61]
I've defined the following grid:

```css
.grid-wrapper {
    /* autoprefixer: off*/
    display: grid;
    grid-template-columns: repeat(15, 1fr);
    grid-gap: 10px;
}
```

I have a following questions about gap:

1. Does it need to be specified for columns and rows or does `grid-gap` work for both?
2. Do gutters count  when using `grid-column` and `grid-row`?
3. I've seen some demos use `grid-template-columns: 1fr repeat(14, 10px 1fr);` instead of `grid-template-columns: repeat(15, 1fr)` with `grid-gap: 10px`. Is there a preferred way to do it? are they equivalent?

Thanks :)
