### ISSUE TITLE
Is it possible to transition or animate between Grid layouts?

### ISSUE THREAD

**Issue by oliverturner** [rachelandrew/cssgrid-ama#74]
For example, can one smoothly animate between

```css
.foo {
  grid-template-columns: 1fr 0fr;
}
```

and 

```css
.foo {
  grid-template-columns: 0fr 1fr;
}
```
The [spec](https://drafts.csswg.org/css-grid/#propdef-grid-template-columns) indicates that one _should_ be able to, where the list is simple, but [this example](https://codepen.io/codedsignal/pen/yboYaa?editors=0100) doesn't work as expected (by me at least!)
